services:
  - type: web
    name: lynkledger-api
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: DATABASE_URL
        fromDatabase:
          name: lynkledger-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lynkledger-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DEBUG
        value: false
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true

  - type: worker
    name: lynkledger-worker
    env: python
    buildCommand: ./build.sh
    startCommand: ./worker.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: DATABASE_URL
        fromDatabase:
          name: lynkledger-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lynkledger-redis
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: lynkledger-api
          envVarKey: SECRET_KEY

  - type: worker
    name: lynkledger-beat
    env: python
    buildCommand: ./build.sh
    startCommand: ./beat.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: DATABASE_URL
        fromDatabase:
          name: lynkledger-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lynkledger-redis
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: lynkledger-api
          envVarKey: SECRET_KEY

databases:
  - name: lynkledger-db
    databaseName: lynkledger
    user: lynkledger
    plan: free

redis:
  - name: lynkledger-redis
    plan: free 