# Generated by Django 4.2.10 on 2025-05-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('organization_type', models.CharField(choices=[('business', 'Business'), ('household', 'Household'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], default='business', max_length=20, verbose_name='organization type')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='logo')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='primary color')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('fiscal_year_start', models.DateField(blank=True, null=True, verbose_name='fiscal year start')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20, verbose_name='role')),
                ('can_manage_members', models.BooleanField(default=False, verbose_name='can manage members')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='can manage settings')),
                ('can_manage_billing', models.BooleanField(default=False, verbose_name='can manage billing')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='can view reports')),
                ('can_create_transactions', models.BooleanField(default=False, verbose_name='can create transactions')),
                ('can_approve_transactions', models.BooleanField(default=False, verbose_name='can approve transactions')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='invitation accepted at')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='last active at')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_sent', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization', verbose_name='organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'organization membership',
                'verbose_name_plural': 'organization memberships',
                'ordering': ['organization', 'user'],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='organizations.OrganizationMembership', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
