# Generated by Django 4.2.10 on 2025-05-23 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organizationinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_invitations_accepted', to=settings.AUTH_USER_MODEL, verbose_name='accepted by'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='invited by'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True, verbose_name='token'),
        ),
    ]
