# Generated by Django 4.2.10 on 2025-05-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_alter_organizationinvitation_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(default='free', max_length=32, verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_organizations', to=settings.AUTH_USER_MODEL, verbose_name='sponsor'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sponsor_type',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('client', 'Client')], default='client', max_length=16, verbose_name='sponsor type'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='pro_features_for_accountant',
            field=models.BooleanField(default=False, verbose_name='pro features for accountant'),
        ),
    ]
