# Generated by Django 4.2.10 on 2025-05-24 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_incentive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentive',
            options={'ordering': ['-created_at'], 'verbose_name': 'incentive', 'verbose_name_plural': 'incentives'},
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='pro_features_for_accountant',
        ),
        migrations.AddField(
            model_name='incentive',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='used at'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='organization',
            name='accountant_incentive_granted',
            field=models.BooleanField(default=False, verbose_name='accountant incentive granted'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='stripe subscription id'),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='trial ends at'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='pro_features_enabled',
            field=models.BooleanField(default=False, verbose_name='pro features enabled'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='pro_features_source',
            field=models.CharField(blank=True, choices=[('accountant_subscription', 'Accountant Subscription'), ('organization_plan', 'Organization Plan'), ('trial', 'Trial Period')], max_length=32, null=True, verbose_name='pro features source'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='granted at'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='type',
            field=models.CharField(choices=[('free_month', 'Free Month'), ('discount', 'Discount'), ('credit', 'Credit'), ('feature_unlock', 'Feature Unlock')], max_length=32, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=32, verbose_name='plan'),
        ),
    ]
