# Generated by Django 4.2.10 on 2025-05-25 19:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0006_alter_incentive_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentive',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incentivo', 'verbose_name_plural': 'Incentivos'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='organizationinvitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invitación a Organización', 'verbose_name_plural': 'Invitaciones a Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Membresía de Organización', 'verbose_name_plural': 'Membresías de Organizaciones'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='incentive',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Usado'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Cliente Stripe'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin de Suscripción'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactiva'), ('active', 'Activa'), ('past_due', 'Pago Pendiente'), ('canceled', 'Cancelada'), ('trialing', 'En Período de Prueba')], default='inactive', max_length=50, verbose_name='Estado de Suscripción'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='type',
            field=models.CharField(choices=[('free_month', 'Free Month'), ('discount', 'Discount'), ('credit', 'Credit'), ('feature_unlock', 'Feature Unlock')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='organizations.OrganizationMembership', to=settings.AUTH_USER_MODEL, verbose_name='Miembros'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Patrocinador'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sponsor_type',
            field=models.CharField(choices=[('accountant', 'Contador'), ('client', 'Cliente')], default='client', max_length=20, verbose_name='Tipo de Patrocinador'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='token',
            field=models.CharField(max_length=100, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
