# Generated by Django 4.2.10 on 2025-05-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_incentive_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='pro_features_for_accountant',
            field=models.BooleanField(default=False, verbose_name='pro features for accountant'),
        ),
    ]
