# Generated by Django 4.2.10 on 2025-05-18 22:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20, verbose_name='account type')),
                ('subtype', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('receivable', 'Accounts Receivable'), ('inventory', 'Inventory'), ('fixed_asset', 'Fixed Asset'), ('payable', 'Accounts Payable'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('sales', 'Sales'), ('service', 'Service Revenue'), ('interest', 'Interest Income'), ('cost_of_goods', 'Cost of Goods Sold'), ('operating', 'Operating Expense'), ('payroll', 'Payroll'), ('tax', 'Tax')], max_length=20, verbose_name='account subtype')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='current balance')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='available balance')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account', verbose_name='parent account')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['code', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='period')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(verbose_name='description')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='reference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('reconciled', 'Reconciled'), ('void', 'Void')], default='draft', max_length=20, verbose_name='status')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='is recurring')),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', max_length=20, verbose_name='recurrence type')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='recurrence end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tax rate')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='exchange rate')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.account', verbose_name='account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'transaction entry',
                'verbose_name_plural': 'transaction entries',
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='amount')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='minimum amount')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='maximum amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='accounting.account', verbose_name='account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.budget', verbose_name='budget')),
            ],
            options={
                'verbose_name': 'budget item',
                'verbose_name_plural': 'budget items',
                'unique_together': {('budget', 'account')},
            },
        ),
    ]
