# Generated by Django 4.2.10 on 2025-05-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('channel', 'Channel')], default='direct', max_length=20, verbose_name='type')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='conversation_icons/', verbose_name='icon')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='system message')),
                ('reactions', models.JSONField(default=dict, verbose_name='reactions')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='conversation')),
                ('mentions', models.ManyToManyField(blank=True, related_name='message_mentions', to=settings.AUTH_USER_MODEL, verbose_name='mentions')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message', verbose_name='parent message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/%d/', verbose_name='file')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('file_size', models.BigIntegerField(verbose_name='file size')),
                ('file_type', models.CharField(max_length=100, verbose_name='file type')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='message_attachments/thumbnails/%Y/%m/%d/', verbose_name='thumbnail')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='message')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'message attachment',
                'verbose_name_plural': 'message attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20, verbose_name='role')),
                ('can_send_messages', models.BooleanField(default=True, verbose_name='can send messages')),
                ('can_add_participants', models.BooleanField(default=False, verbose_name='can add participants')),
                ('can_remove_participants', models.BooleanField(default=False, verbose_name='can remove participants')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='can manage settings')),
                ('muted_until', models.DateTimeField(blank=True, null=True, verbose_name='muted until')),
                ('desktop_notifications', models.BooleanField(default=True, verbose_name='desktop notifications')),
                ('mobile_notifications', models.BooleanField(default=True, verbose_name='mobile notifications')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='last read at')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.conversation', verbose_name='conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'conversation member',
                'verbose_name_plural': 'conversation members',
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='messaging.ConversationMember', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
    ]
