# Generated by Django 4.2.10 on 2025-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_features',
            field=models.BooleanField(default=False, verbose_name='pro features'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='stripe customer id'),
        ),
    ]
